### ISSUE TITLE
Tracking uninstalls

### ISSUE THREAD

**Issue by jzeferino** [mparticle-integrations/mparticle-android-integration-appsflyer#15]
Hi, when reading the documentation from [mParticle](https://docs.mparticle.com/integrations/appsflyer/event/) I see that uninstall tracking is supported. But I can't find any documentation to that. Only documentation I see is on [AppsFlyer](https://support.appsflyer.com/hc/en-us/articles/210289286#Android-Uninstall) page but that assumes the Appsflyer sdk is installed.

Can you guys point me in the right direction please?

**Comment by samdozor** [comment]
Hi @jzeferino yes those docs are referring to the fact that since the full AppsFlyer SDK is present (as a dependency of the kit), uninstall tracking is supported. Unfortunately since it requires AndroidManifest.xml changes (as referenced in AppsFlyer's doc), there's no way for the kit to programmatically enable this on AppsFlyer (lest we force all AppsFlyer kit customers to have the manifest change).

So you should be able to follow those docs exactly and it will work with the AppsFlyer kit provided by mParticle.

**Comment by jzeferino** [comment]
Thanks for your reply. Just to finalize, there is no need to explicitly implement the AppsFlyer sdk correct?

**Comment by willpassidomo** [comment]
hey @jzeferino sorry about that, I think this thread got dropped prematurely. In case it's still relevant, you are correct, you do not need to explicitly implement the Appsflyer as long as the MParticle Appsflyer kit is enabled and running. One thing to note, the MParticle SDK fetches and caches your Appsflyer credentials so, the Appsflyer initialization is an asynchronous process and it won't necessarily be initialized immediately after `MParticle.start()` finishes.
