### ISSUE TITLE
including kit causes network calls on app startup

### ISSUE THREAD

**Issue by brian-plummer-okcupid** [mparticle-integrations/mparticle-android-integration-appsflyer#97]
We have observed network calls to the url:

https://2nz8lq-[*].appsflyersdk.com/v1.0/android/com.ourpackage?af_sig=e2a454b3dd63f4f39287easdfdsafa4748cda5sdfds24a2fb&sdk_version=6.10

another example:

https://2nz8lq-conversions.appsflyersdk.com/api/v6.10/androidevent?app_id=com.ourpackage&buildnumber=6.10.0

Is there a way to granularly turn this on/off

**Comment by einsteinx2** [comment]
I just took a look at the Kit code, which is our wrapper around the AppsFlyer SDK: https://github.com/mparticle-integrations/mparticle-android-integration-appsflyer/blob/main/src/main/kotlin/com/mparticle/kits/AppsFlyerKit.kt

The only thing we do on launch other than initialize their SDK is request the AppsFlyer UserID (required for mParticle to utilize the AppsFlyer integration) and enable deep linking support (https://github.com/mparticle-integrations/mparticle-android-integration-appsflyer/blob/7dc188b28561dceff605fb8c44e463872cc3844a/src/main/kotlin/com/mparticle/kits/AppsFlyerKit.kt#L53).

I'm not sure if that's what's causing this, but those URLs are AppsFlyer URLs and are likely part of their SDK initialization process.

To directly answer your question, there is no way to granularly disable these other than disabling the AppsFlyer kit entirely in the mParticle interface.

Since this appears to be normal AppsFlyer SDK behavior and not something we're explicitly doing in the Kit code, this doesn't appear to be a bug. Remember you always have direct access to the AppsFlyer SDK (and any SDK that our kits wrap), so you may want to either discuss with them what these URL calls are doing and if/how they can be disabled and then call into the SDK directly to do so, or speak with your mParticle contact about an enhancement request to add support for controlling Appsflyer initialization (though to be clear I'm not sure there's anything we can do about this on our end if just initializing the Appsflyer SDK causes it, which you would need to confirm with them).
